### ISSUE TITLE
sluggish scrolling on Catalina

### ISSUE THREAD

**Issue by chrschm** [geany/geany-osx#12]
Hi,

since upgrading to Catalina (Geany 1.36) scrolling through files is kind of sluggish.
(Very) slow scrolling seams to be fine, but fast scrolling leads from delay of the displayed text to complete stop of scrolling while still spinning the mouse wheel.
Feels like this could be a rendering issue as the displayed text sometimes won't change or double.
Also plain text files seem to be not that affected as files with syntax highlighting.

**Comment by techee** [comment]
Yep, I did run into the same issue. Have a look at https://github.com/geany/geany/issues/2344 where I created a build based on GTK3 instead of GTK2 which seems to work much better.

**Comment by chrschm** [comment]
Works a lot better now, even if not perfect. Thank you.

**Comment by techee** [comment]
> Works a lot better now, even if not perfect

Is there still some problem with the performance or redrawing? It works really well for me. Of course, this is a GTK application and Scintilla doesn't support smooth scrolling, only line by line, so it won't be like XCode or some native editor.

**Comment by chrschm** [comment]
I guess its ok. At least its not conspicuous.
