### ISSUE TITLE
1.36 Mac bundle can not input chinese

### ISSUE THREAD

**Issue by xuanyuanhuairen** [geany/geany-osx#16]
On Mac OS X , i can't use input chinese with the default chinese input method. When i input chinese in the editor, the editor still display english chars.

**Comment by xuanyuanhuairen** [comment]
problem solved , this problem only exists in geany-1.36_osx-2.dmg ,and after i try the old version of https://download.geany.org/geany-1.36_osx.dmg this problem solved.

**Comment by techee** [comment]
I didn't enable IME by default because of some minor problems with it in geany-1.36_osx-2.dmg. But when you set
```
im_module=quartz
```
inside
```
~/.config/geany/geany_mac.conf
```
it should work also with `geany-1.36_osx-2.dmg`.

**Comment by techee** [comment]
This is hopefully fixed in Geany 1.37. Closing.
