### ISSUE TITLE
Default VTE font is too small

### ISSUE THREAD

**Issue by codebrainz** [geany/geany-osx#2]
It's fantastic that VTE is working now!

I noticed by default the font is super small though, I think it's set to like "Monospace 10" or something (which ends up being Courier New 10pt here, rather than a more typical Mac monospace font), I think it should be more like 13pt size by default.

**Comment by techee** [comment]
I used 12pt for the rest of the fonts so better 12pt for the terminal too. I'll send a patch to Geany to set a different default size on OS X.
