### ISSUE TITLE
Long startup times after upgrade to 1.37

### ISSUE THREAD

**Issue by frlan** [geany/geany-osx#20]
After upgrading to 1.37-2 the startup with about 20-30 files takes ~10s on my 10.15,7 -- before it was <<5s

**Comment by techee** [comment]
Have you also tried 1.37-3? Are there any differences in startup times when no files are opened? Do you use some plugins, e.g. ProjectOrganizer that could do some extra work?

**Comment by codebrainz** [comment]
Likely totally unrelated, but I noticed on Windows it takes quite a while to startup too, maybe 5-10 seconds with 0-1 files open.

**Comment by techee** [comment]
At least on my machine it's around 2s to start with 1 file open - and I think it was about the same time with previous releases too (I think it's mainly because all the dylibs that have to be loaded plus signing verification).

**Comment by b4n** [comment]
@techee could you test https://github.com/geany/geany/pull/2747 and see if that fixes that one as well?  I would think it does, but well, who knows.

**Comment by b4n** [comment]
@techee I didn't mean to close this, I didn't expect GitHub to do so because of the mention in the PR's description.  Please reopen if it does *not* fix it, although it most probably did.
