### ISSUE TITLE
MacOS:  rectangular selection not possible with just keys

### ISSUE THREAD

**Issue by journeyresearch** [geany/geany-osx#25]
On Linux, it is possible to use only keys to make a rectangular selection, but on a Mac, this appears to be broken.  Using Ctrl-Shift with the mouse works, but I'd rather use keys.

Geany 1.37
Using GTK+ v3.24.20 and GLib v2.66.0 runtime libraries

System Version:	macOS 10.15.7 (19H15)
Kernel Version:	Darwin 19.6.0

Perhaps I need to change a keybinding? (attached)
[keybindings.conf.gz](https://github.com/geany/geany/files/5643579/keybindings.conf.gz)

**Comment by techee** [comment]
Doesn't Option+Shift plus arrows work? It at least works on my machine.

**Comment by techee** [comment]
I'm closing this as I think rectangular selection using keys is possible - Option+Shift+arrows works for me. Feel free to reopen this issue if it isn't the case for you.

The real issue though is the one reported in

https://github.com/geany/geany/issues/2685
