### ISSUE TITLE
Emoji not displayed

### ISSUE THREAD

**Issue by djwashburn** [geany/geany-osx#27]
I cannot see emoji characters in the editor. The emoji keyboard shortcut (Ctrl + Cmd + Spacebar) also does not work within this app. They can be pasted, and successfully copied back out, but they are invisible.

On macOS Big Sur 11.5.1, Intel chip.

**Comment by techee** [comment]
I've seen this problem too but I don't know what the problem could be. I actually think it's not a font problem but rather something in pango or other font rendering library.

**Comment by elextr** [comment]
It looks like two things:

- invisible emojis, which could indeed be GTK/Pango, which version are you using? And just for the record I have Pango 1.44 and Hack regular font set and emojis show (on Linux).
- Ctrl+Cmd+spacebar not working, and obviously doesn't work here due to no Cmd key :grin:  The Ctrl+Shift+u unicode entry sequence is baked into GTK, and Mattias has refused to make it configurable, so I'm not sure how easy it will be to make the mac sequence work, without adding code to intercept it and insert the emoji yourself.

**Comment by techee** [comment]
Well, I rather suspect the GTK -> macOS interaction wherever this happens (my guess is Pango macOS backend). It's not about inserting such characters, opening existing file with emoji doesn't work either. Font shouldn't be the issue because the same font used in a native macOS editor works fine.

**Comment by djwashburn** [comment]
I don't know what GTK/Pango version, I just installed geany. How would I check the version of dependencies like Pango? And I would confirm what techee said above.

**Comment by elextr** [comment]
> Well, I rather suspect the GTK -> macOS interaction wherever this happens (my guess is Pango macOS backend).

Yeah, likely, and I'm afraid thats about as helpful as I can be with macOS :grin:

@djwashburn does the ctrl+cmd+spacebar insert an emoji that doesn't display but you can copy out the file, or are you reporting that it doesn't insert one either, seems @techee and I read your report differently.

**Comment by djwashburn** [comment]
Ctrl+Cmd+Spacebar does not even open the emoji keyboard in Geany. It is
then necessary to copy and paste emojis from elsewhere, and it is then
*also* true that they are invisible once pasted. Two separate problems, I
imagine.

**Comment by djwashburn** [comment]
Any updates on this issue? I know this may seem trivial, but I consider it to be an essential feature. Emoji are a part of the unicode standard and are supported now by every operating system. I will probably switch to another editor if this is not resolved.

**Comment by techee** [comment]
I'm afraid this doesn't depend on Geany itself but on other libraries used by Geany and since the problem existed for several years, I'm afraid nobody is working on it.

**Comment by elextr** [comment]
@techee I suppose emojis display in Scite for OSX (which does not use GTK)?  If you get a chance it might just be worth checking.

**Comment by techee** [comment]
Actually they don't display (only ??s are shown instead of the unicode characters) which is quite surprising - I assumed they would be shown since SciTE doesn't use the GTK backend (and therefore pango & friends). So it could actually be some Apple-specific Scintilla problem.

**Comment by elextr** [comment]
Hmmm, seems to have been an issue for a while https://github.com/geany/geany/issues/771#issuecomment-196003341

"Emoji" doesn't exist in Geany code (including Scintilla) and I can't figure out how to search in saucefudge Scintilla murcurial so who knows.

[Edit: What I mean is who knows if any patches have been applied since LTS Scintilla]

**Comment by elextr** [comment]
@techee I guess its obvious, but better to ask, I am presuming emojis show in other apps using the _same font_?

**Comment by djwashburn** [comment]
Yes, I have all my editors set to Fira Code, and emoji appear in the other editors. Though I imagine the emoji are not actually being displayed in Fira Code, but in a fallback font, probably https://en.wikipedia.org/wiki/Apple_Color_Emoji

**Comment by elextr** [comment]
Ahhh, I don't think Scintilla does fallback fonts, the style for a lexical entity can only set one font, no fallback list.

**Comment by b4n** [comment]
@elextr Fallback should be handled by Pango or its backend, Scintilla shouldn't have anything to worry about in this area.  The same happens on Linux, most fonts don't have all the emoji but a fallback is used for the missing ones (Noto in most cases I guess).
However, this could be indeed a fallback issue on OSX, or fonts not accessible from Geany's runtime or such?  /me is not macos-literate so wouldn't know though.

**Comment by elextr** [comment]
How does OSX do fontconfig, probably not like linux I guess?

**Comment by elextr** [comment]
@b4n, note above @techee also found Scite OSX (which is not Pango) doesn't do emojis.

**Comment by techee** [comment]
OK, my bad, I used incorrect file encoding in SciTE on macOS - when set to utf-8, emoji displays correctly there. So it looks like some macOS-GTK-backend-related problem.

**Comment by techee** [comment]
For reference, I think this is the corresponding pull request in cairo:

https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/9

**Comment by rastapopougros** [comment]
I have the exact same problem but on Ubuntu (recent, 22.04, gnome 42.1), and I didn't see other issue on the subject on the central geany repo. I can paste emojis from elsewhere, but always render in blank characters.

**Comment by elextr** [comment]
@rastapopougros if there is no issue for Ubuntu in the main repository, then open one, this is for macos specific issues.

**Comment by techee** [comment]
I've just made the following builds:

Geany 1.38 built with the latest GTK and other dependencies, including some extra fixes which I plan to release as the official macOS build on the Downloads page unless there are some problems with it:
https://download.geany.org/snapshots/geany-1.38_osx-5.dmg
https://download.geany.org/snapshots/geany-1.38_osx_arm64-2.dmg

Like the above but Geany and plugins are from current git master:
https://download.geany.org/snapshots/geany-1.38_osx.dmg
https://download.geany.org/snapshots/geany-1.38_osx_arm64.dmg

Emoji work thanks to a fix in cairo! Geany can finally be used for some serious coding on macOS ;-).
