### ISSUE TITLE
Geany 1.38 does not start on MacOS

### ISSUE THREAD

**Issue by alexFRD77** [geany/geany-osx#28]
After the latest update (universal builds) Geany doesn't launch at all, "Service exited with abnormal code: 1 " in system.log.  I've found no issues when forcing Rosetta though.
Im using a Macbook Air with arm chip.

**Comment by poorlymac** [comment]
Might be

% /Applications/Geany.app/Contents/MacOS/geany ; exit;
2021-10-12 09:32:46.364 geany[50041:1834806] dlopen() failed (possibly unsigned libgeany.0.dylib)

**Comment by techee** [comment]
Is this fixed with the release here:

https://download.geany.org/geany-1.38_osx-3.dmg

For testing, I also created an ARM version of Geany here:

https://download.geany.org/snapshots/geany-1.38_osx_arm64.dmg

**Comment by techee** [comment]
I think this is fixed now. If not, please feel free to reopen this issue.
