### ISSUE TITLE
Geany 1.38 fails on MacOS Big Sur M1 Chip

### ISSUE THREAD

**Issue by Anterotesis** [geany/geany-osx#29]
Starting Geany 1.38 on MacOS Big Sur, on a Macbook with an M1 chip results in the message:
"Service exited with abnormal code: 1"
Works as normal on Intel Mac running Catalina.

**Comment by techee** [comment]
Even though right now I don't have access to an M1 mac (had to return my development transition kit to Apple), I have a suspect - I think with the latest XCode the launcher gets compiled both for Intel and ARM but the rest of the binaries is Intel-only so the launcher is started as an ARM process but then loading the code from dylibs fails as they are Intel.

I tried to disable ARM code generation for the launcher and uploaded a new installer for you to test - would you give the following file a try?

https://download.geany.org/snapshots/geany-1.38_osx-2.dmg

**Comment by Anterotesis** [comment]
It works! Thanks very much.

**Comment by techee** [comment]
Good to hear. I just moved this new binary to the download directory here

https://download.geany.org/geany-1.38_osx-2.dmg
