### ISSUE TITLE
spellcheck doesn't see dictionaries on macOS after upgrading to Geany 1.38

### ISSUE THREAD

**Issue by danpla** [geany/geany-osx#30]
I've updated Geany to 1.38 (geany-1.38_osx-2.dmg) and found that it no longer sees the dictionaries. In debug messages I found that Enchant is now 2.2.15 (was 1.x in Geany 1.37), so, as README suggests, I moved the dictionaries to the "hunspell" subdirectory while leaving the path in the configuration dialog untouched (parent directory of "hunspell"). Unfortunately, this didn't help, and the plugin still gives error "The Enchant library couldn't be initialized (unknown error (maybe the chosen language is not available))".

**Comment by techee** [comment]
I haven't tried it but at least from this code

https://github.com/AbiWord/enchant/blob/ff5e31d0535ba93f27010a6b1ac50e87252bd759/src/lib.c#L116

it seems that enchant gets the config files from `~/.config/enchant` (`g_get_user_config_dir()` should return `~/.config` here). So you could try moving the dictionaries there.

**Comment by danpla** [comment]
Unfortunately, moving dictionaries to ~/.config/enchant doesn't seem to help.

**Comment by techee** [comment]
There was indeed a problem where the enchant library didn't correctly find the corresponding spelling module. I created a new build here, would you give it a try?

https://download.geany.org/snapshots/geany-1.38_osx.dmg

**Comment by danpla** [comment]
It seems like in this build, the plugin shows language names from the `/Applications/Geany.app/Contents/Resources/share/enchant/AppleSpell.config` file (seems to be  https://github.com/AbiWord/enchant/blob/master/providers/AppleSpell.config) and ignores user's dictionaries.

`Applications/Geany.app/Contents/Resources/lib/enchant-2` directory only has `enchant_applespell.so`, so maybe there should be the Hunspell plugin instead (or in addition to)?

**Comment by techee** [comment]
OK, one more attempt - hunspell is now compiled and enchant_hunspell.so module is also added to the bundle. The download link is the same as before. Does it work now?

**Comment by danpla** [comment]
It seems to work now. I have Russian.dic and en_US.dic files; Russian is now in the list, but since the languages from AppleSpell.config are still there, I'm not sure whether en_US is my dictionary file or the one from AppleSpell.

Thanks!

**Comment by techee** [comment]
> I'm not sure whether en_US is my dictionary file or the one from AppleSpell.

You can rename the `en_US` hunspell dictionary files e.g. to `en_US1` and then you'll have both dictionaries side by side.

**Comment by techee** [comment]
Closing as I believe it's fixed now.
