### ISSUE TITLE
Window shows black screen upon opening

### ISSUE THREAD

**Issue by jrusse1** [geany/geany-osx#31]
I'm trying to run Geany 1.38 on the new MacBook Pro 14" with M1 Pro and 16 GB RAM. When I open Geany, I can't do anything in the program and the window shows a black screen. This has worked until I installed Xcode and an update for Final Cut. I'm not sure which, if any, of these updates are causing the issue. I uninstalled Xcode to see if there was some weird compatibility issue, uninstalled/reinstalled Geany multiple times, restarted my Mac, and booted into safe mode, but I always got the same results.  Any ideas on how to get this to work? 
Screenshot:
<img width="1512" alt="Screen Shot 2021-10-28 at 8 46 53 PM" src="https://user-images.githubusercontent.com/93357728/139355745-c267bec5-0299-44e5-9cc0-7d7926681a93.png">

**Comment by techee** [comment]
I get the same problem after installing macOS Monterey. I'll try to rebuild with the latest gtk-osx

https://gitlab.gnome.org/GNOME/gtk-osx

There seems to be a patch related to macOS 12 that could possibly fix this problem.

**Comment by jrusse1** [comment]
Thanks, glad to know this isn't just me. It worked on Monterey for a bit but I think the system update for Final Cut broke it.

**Comment by techee** [comment]
Would you try the snapshot from here:

https://download.geany.org/snapshots/geany-1.38_osx-3.dmg

Basically I just rebuilt Geany with the latest version of gtk-osx with all the macOS 12 patches and it seems it fixed the problem at least on my Intel-based macbook.

**Comment by jrusse1** [comment]
That fixed it!

**Comment by techee** [comment]
Good to hear. I moved the installer to the usual place here:

https://download.geany.org/geany-1.38_osx-3.dmg
