### ISSUE TITLE
Geany 1.38 only shows black app area on macOS Monterey

### ISSUE THREAD

**Issue by willbprog127** [geany/geany-osx#36]
On macOS 12.2.1 Monterey, Intel processor and AMD FirePro D300 graphics card, Geany 1.38 shows only a black app area.  Pulling up the 'About...' dialog only shows a title bar with nothing below it.  Please see attachment.

![geany-black-editor-issue](https://user-images.githubusercontent.com/1296250/155245478-266a4882-d09b-4cc2-8c5a-d09341f66c63.png)

Geany 1.3.7.1 does _not_ have this issue and works fine on macOS Monterey.

**Comment by techee** [comment]
This looks like one of the problems with the original binary I made after the 1.38 release. In the meantime I made a new binary fixing various issues - do you get this behavior when you download the latest release from

https://www.geany.org/download/releases/

**Comment by willbprog127** [comment]
> do you get this behavior when you download the latest release from

I have tried today with the geany-1.38_osx-4.dmg release and it is working properly.  Thank you! 👍
