### ISSUE TITLE
geany `+quartz` on Apple Silicon / M1 CPU does not have correct icon and does not work with Alt-Tab app

### ISSUE THREAD

**Issue by simonhf** [geany/geany-osx#38]
Just upgraded from an Intel to Apple Silicon MacBook and re-installed geany, but have come across the following problems:

Problem geany/geany#1: Solved: Non-`+quartz` geany fails to work correct on M1 and UI glitches. However, geany `+quartz` works with perfect looking UI.

Problem geany/geany#2: Unsolved: The icon (shown in the Mac bar at the bottom of the screen, or when pressing Command + Tab to switch apps) of the geany `+quartz` while running, is just a black square with the words 'exec' in the top left hand corner.

Problem geany/geany#3: Unsolved: The Mac Alt-Tab app [1] fails to recognize geany as an app and doesn't display it in its list windows to switch to.

[1] https://github.com/lwouis/alt-tab-macos/issues/1858

**Comment by techee** [comment]
If I understand correctly, you are using MacPorts and Geany is started as a command-line app when using it without being properly packaged to an app bundle which results in the various problems you describe.

Geany, however, provides both x86 and arm64 app bundles here https://geany.org/download/releases/ which are properly signed and notarized with Apple and these issues shouldn't be present there.

**Comment by simonhf** [comment]
@techee Thanks for the quick response. Yes, I installed Geany like this via MacPorts:

```
$ sudo port install gtk3 +quartz
$ sudo port install geany +quartz
```

I tried out your suggestion to install via the bundle and now everything works fine. Thanks!

**Comment by simonhf** [comment]
Also, created a MacPorts issue here [1] :-)

[1] https://trac.macports.org/ticket/65660#ticket
