### ISSUE TITLE
Right-click submenu action stopped working

### ISSUE THREAD

**Issue by JanAxelsson** [geany/geany-osx#43]
The right-click menus, and submenues appear.  But the action when clicking a submenu stopped working. Was working earlier.

I suspect that it was a homebrew command (not related to geany) that destroyed this, maybe changing GTK (saw that flashing by).  I am not sure, though.

Geany was installed using your install files, and initially working.  I have reinstalled from downloaded installer, but did not help.  I have after this issue appeared, also tried a homebrew install of geany, but exactly the same problem also then.  

I am a bit confused, because I thought a MacOS app was selfcontained.  Please help advise me on how to get my favourite Geany editor to work again.

Screen recording showing that neither copying or inserting comments works :
https://user-images.githubusercontent.com/29306454/226905053-bfd11d7d-6383-4ac3-86ca-83baba7d4ab7.mp4

**Comment by elextr** [comment]
Geany OSX/Macos has its own repo and issues, moving.

**Comment by techee** [comment]
Interesting. I see the same problem with the official releases but recently I made new binaries with the latest gtk-osx here and these don't seem to exhibit the problem:

https://download.geany.org/snapshots/geany-1.38_osx_arm64.dmg
https://download.geany.org/snapshots/geany-1.38_osx.dmg

These binaries use newer version of GTK with some macOS 13 fixes so maybe this is the reason.

**Comment by JanAxelsson** [comment]
Thanks!

This works great — tested on the arm64 version

/Jan

**Comment by techee** [comment]
OK, great. Just curious, are you using macOS 13?

**Comment by JanAxelsson** [comment]
Ventura, whatever version that is/JanSkickat från min iPhone22 mars 2023 kl. 18:40 skrev Jiří Techet ***@***.***>:﻿
OK, great. Just curious, are you using macOS 13?

**Comment by techee** [comment]
> Ventura, whatever version that is

OK, so it's 13 (I remember the numbers, not the names ;-)

**Comment by JanAxelsson** [comment]
My turn to be curious. I am so amazed about response time for this and previous issues I have posted. Does Geany have developers that are somehow supported so you don’t have to do all development on your own time?  If so, is it big companies chipping in?Happy if you answer, but understand if you don’tThanks for Geany from a user since maybe 15 years/JanSkickat från min iPhone22 mars 2023 kl. 21:27 skrev Jiří Techet ***@***.***>:﻿

Ventura, whatever version that is

OK, so it's 13 (I remember the numbers, not the names ;-)

**Comment by techee** [comment]
Nah, you were just lucky that I noticed this quickly and had time to test it and reply (@elextr on the other hand seems to be always on :-).

**Comment by elextr** [comment]
> @elextr on the other hand seems to be always on

By the majik [sic] of time zones it can seem that way :smile:

**Comment by techee** [comment]
I've just made the following builds:

Geany 1.38 built with the latest GTK and other dependencies, including some extra fixes which I plan to release as the official macOS build on the Downloads page unless there are some problems with it:
https://download.geany.org/snapshots/geany-1.38_osx-5.dmg
https://download.geany.org/snapshots/geany-1.38_osx_arm64-2.dmg

Like the above but Geany and plugins are from current git master:
https://download.geany.org/snapshots/geany-1.38_osx.dmg
https://download.geany.org/snapshots/geany-1.38_osx_arm64.dmg

Both of these builds should fix this problem.
