### ISSUE TITLE
Hierarchical view for document list

### ISSUE THREAD

**Issue by cloudis-ild** [geany/geany-osx#46]
MacBook Pro, Ventura 13.4.1

Whilst working through the resolution of a previous issue (https://github.com/geany/geany-osx/issues/42)  one pre-release version of Geany was able to show the document list as a hierarchical tree rather than a flat list.  The subsequent release build (Sulamar 1.38 2023-03-25 with GTK+ v3.24.36 and GLib v2.72.0)) excluded this feature. Is there a setting to switch on the hierarchical view, or is it new feature which needs to be requested?

**Comment by elextr** [comment]
The current Geany Git has a "show tree" in the documents pane right click menu.  So it will be in the next release.

**Comment by cloudis-ild** [comment]
Excellent, thanks.
