### ISSUE TITLE
How to change matching brace color in Geany v2.0 ?

### ISSUE THREAD

**Issue by that-ben** [geany/geany-osx#50]
Might be related to or even a duplicate of geany/geany#885 but I could not figure it out.  I'm new to Geany.

<img width="280" alt="Screenshot 2023-11-10 at 1 08 55 PM" src="https://github.com/geany/geany/assets/13210399/282df898-199e-4826-985b-dee5058c3167">

If it means anything, I'm currently using the "Kary Pro Colors - Bare Dark" scheme.

**Comment by elextr** [comment]
Same as geany/geany#885, to change a colour scheme you have to edit the colour scheme file you are using and change the setting geany/geany#885 mentioned.

**Comment by that-ben** [comment]
Alright, so given that I'm using the "Kary Pro Colors - Bare Dark" scheme, I can still launch this to access the file you're talking about, correct?
 
<img width="1363" alt="Screenshot 2023-11-10 at 5 32 16 PM" src="https://github.com/geany/geany/assets/13210399/4a4bef79-1872-4437-887e-8749c3ab9e0b">

**Comment by elextr** [comment]
No, `filetypes.common` is the default colour scheme, you need whatever file you installed for the one you are using.

**Comment by that-ben** [comment]
I did not install any, I selected "Kary Pro Colors - Bare Dark" from the list of bundled schemes like this:

<img width="1153" alt="Screenshot 2023-11-10 at 5 41 11 PM" src="https://github.com/geany/geany/assets/13210399/6f08511a-1fa9-43d3-8d37-21da34a408b8">

I'm sorry if I'm infuriating long time users with this question right here, but I'm a complete Geany n00b so I have no clue what I'm doing! 🤣 Where should I look for that file exactly?

**Comment by elextr** [comment]
What OS are you using?

**Comment by that-ben** [comment]
macOS Sonoma on a brand new iMac M3 that I received yesterday.  Found this by following the location that's appearing in my previous screenshots in the window's title bar, but that folder is empty :(
<img width="566" alt="Screenshot 2023-11-10 at 5 52 44 PM" src="https://github.com/geany/geany/assets/13210399/d4c5b258-8e01-460d-9c65-f131dece7366">

**Comment by elextr** [comment]
Oh, apples are things I eat, not compute so I can't help you.  But there is a mac specific issues for Geany so I'll transfer this issue to there.

**Comment by that-ben** [comment]
But isn't Geany OS agnostic? I mean it doesn't even use the native open/save dialog interface.

**Comment by elextr** [comment]
Geany is, but system file layouts are not.

**Comment by elextr** [comment]
No, Geany uses GTK on all platforms, never the native dialogs.

**Comment by elextr** [comment]
In case its any help for you finding them colour schemes on Linux are in `${PREFIX}/share/geany/colorschemes` or `${HOME}/.config/geany/colorschemes`.

**Comment by that-ben** [comment]
Found this... progress?

<img width="1286" alt="Screenshot 2023-11-11 at 8 11 35 AM" src="https://github.com/geany/geany-osx/assets/13210399/dcd1ce3e-acf3-4aa5-9083-dd64183971ca">

Now in the appropriate color scheme, I see these brace lines, what do you think I should edit?

<img width="1488" alt="Screenshot 2023-11-11 at 8 03 44 AM" src="https://github.com/geany/geany-osx/assets/13210399/bd321a08-adc3-461b-807a-145057b4bb9e">

I tried to change the following line and chose 0xff0000 just to make sure it's apparent enough, I saved the file, quit Geany, re-launched it and it's still the same as before.  I also selected another color scheme, quit Geany, re-launched, selected the modified color scheme again, but it's still the same.

brace_good=pro_orange,0xff0000;true;false

**Comment by that-ben** [comment]
Found it.  Geany 2.0 comes with a few broken color scheme templates.  Look at the brace_good line, whoever made those bundled schemes typed a comma instead of a semicolon!

When I fix the broken scheme, it now works properly.  If the Geany programmer sees this, the default line should be reading:

`brace_good=pro_orange;pro_selection_background;true;false`

Perhaps this should be fixed before releasing v2.0.1 ... make sure to check the light scheme from the same name also as it contains the same typo! ;-)

**Comment by elextr** [comment]
The bundled colour schemes are from [this collection](https://github.com/geany/geany-themes).  Note its a collection, not made, tested or guaranteed by Geany devs.  You could try raising an issue there so it doesn't get lost, the colour scheme contributors don't neccessarily watch the code repo, or even better make a PR.

**Comment by that-ben** [comment]
Thanks @elextr I raised the issue over on the other GH, so I guess this one here can be closed.
