### ISSUE TITLE
"Change Font" does not seem to have effect

### ISSUE THREAD

**Issue by rovf** [geany/geany-osx#53]
Environment:
MacOS 12.7.3
Geany 1.38
Color Schema: Metallic Bottle

When I use View/ChangeFont and select a different font, not actual font change happens - neither in the user interface nor in the edit pane. I wonder what the "Change Font" function is actually supposed to be for?

**Comment by elextr** [comment]
When you say you "select" a new font do you mean you click on one in the dialog list, or do you mean you clicked on the select button which accepts the selection from the list and closes the dialog?

**Comment by rovf** [comment]
I got a list of fonts, and double-clicked on a different font than the one currently selected. But just doing a single click on the font, and then clicking the select button, has no effect either.

**Comment by elextr** [comment]
Ok, just checking, since that (and double click) works here its probably a Macos specific issue, transferring to that issues.

**Comment by techee** [comment]
Hmm, works for me (on Geany 2.0, macOS 14.3.1). I haven't tried 1.38 - could just be a bug in the older GTK shipped with that release. Do you have any specific reason for not using Geany 2.0?

**Comment by rovf** [comment]
Well, simply that I did not know that 2.0 is available for MacOS already. Sadly, Geany does not have a builtin update checker. What do I have to do for updating it, in order to have my old settings (preferences, list of recent files etc.) preserved? I guess if I just download the dmg file for 2.0, I get a clean, new copy and all my settings are gone.

**Comment by techee** [comment]
Settings should be preserved - `~/.config/geany` isn't modified in any way when you copy-over the binary.

**Comment by rovf** [comment]
Just tried it on Geany 2.0. Same effect. Font does not change. I tried the change from the font Jet Brains Mono Medium to the font Jet Brains Mono Light Italic (on the grounds that if I change to an italic font, the change would be immediately visible).  In the status bar, I get the message

    14:49:51: Font updated (JetBrains Mono Light Italic Condensed 17).

but the font itself does not change.

**Comment by elextr** [comment]
Ahh, if you are only changing the font face it will have no effect, the face and weight (bold) are both part of the styles controlled by the colour scheme.  Maybe try changing actual font, or the size.

**Comment by rovf** [comment]
Ah, I see. This works indeed.

**Comment by eht16** [comment]
As a side note:
> Well, simply that I did not know that 2.0 is available for MacOS already. Sadly, Geany does not have a builtin update checker. 

There is the UpdateChecker plugin (https://plugins.geany.org/updatechecker.html) which is probably also included in the macOS bundle.

Can this be closed?

**Comment by rovf** [comment]
The Update Checker does not show up in the Plugin List of Geany, and looking at the website for the updatechecker, I see no installation instructions for MacOS. My guess is that it is not implemented yet for the Mac.

The font issue can be closed. I think I will open an issue for making the updatechecker available for MacOS.

**Comment by techee** [comment]
If I remember correctly, I didn't manage to compile/configure gnutls correctly so https didn't work which is needed for the update checker plugin. Maybe things have changed, I just haven't tried recently.

**Comment by elextr** [comment]
As a side note, web libraries (like Gnutls) are quite active as they address CVEs, so using a non-native library that is included in your release means you would be releasing a continuous stream of security updates.  It should use a native library that is part of Macos and so is regularly updated by that platform and doesn't require Geany to be updated to fix.

**Comment by techee** [comment]
> As a side note, web libraries (like Gnutls) are quite active as they address CVEs, so using a non-native library that is included in your release means you would be releasing a continuous stream of security updates. It should use a native library that is part of Macos and so is regularly updated by that platform and doesn't require Geany to be updated to fix.

Probably not a big issue for the update checker plugin where it connects only our trusted geany.org domain (or similarly the geniuspaste plugin) but I can imagine such issues when e.g. compiling webkit for the markdown plugin - this is why I didn't spend much time trying it.
