### ISSUE TITLE
Bug in Geany theme

### ISSUE THREAD

**Issue by rovf** [geany/geany-osx#54]
MacOS 12.7.3 with Geany 1.38

I'm using the colour scheme called "Metallic Bottle" to edit Ruby programs. The thema is very pleasant to use, but has one problem: It colours Ruby symbols  in the same colour, which is also used as the background for highlighting. This means that if I have a statement

    `attr_reader :abcd`

and select the :abcd with the mouse, I can't read anything, because foreground and background are the same colour. 

I wanted to fix it locally, but can't find the definition file for this thema. BTW, my `.config/geany/colorschemes` directory is empty; I don't know where the Geany installer put its theme files.

**Comment by elextr** [comment]
On Linux its in `$PREFIX/share/geany/colorschemes` but not sure where it is on Macos.

**Comment by techee** [comment]
You can either copy it from 
```
/Applications/Geany.app/Contents/Resources/share/geany/colorschemes
```
or from https://github.com/geany/geany-themes. After its modification you can just copy it under `.config/geany/colorschemes`.

**Comment by rovf** [comment]
I found the theme, but I can't recognize, which setting effects the colouring of Ruby symbols (i.e. a colon, followed by alphanumeric characters). The symbol as such is recognized as syntactic entity, because it is coloured differently; just which setting in the theme file affects this colour?

**Comment by techee** [comment]
Maybe you don't want to modify the theme but the ruby filetype settings: Tools->Configuration Files->Filetype Configuration->Scripting Languages->filetypes.ruby. Under the `[styling]` section you apply the colors defined in the theme to the syntactic features of the given language. The commented-out lines are the default assignments.

**Comment by rovf** [comment]
Good point. I see that symbols are coloured in the theme as _preprocessor_. I don't need to change the filetype settings, but simply can set the desired colour in the theme for the token "preprocessor". Thanks a lot. Issue solved for me. Still I think it would be a good idea, if the theme bundled with Geany, would also fix this. Having a syntactic element in the same foreground colour as the selection colour, leads to trouble.

**Comment by techee** [comment]
The extra themes are taken from https://github.com/geany/geany-themes so you can submit a pull request fixing the bug.

**Comment by techee** [comment]
Closing here in favor of https://github.com/geany/geany-themes/issues/70
